# Requirements as of July 2024
name: gemgis_env
channels:
  - conda-forge
dependencies: 
  - python>=3.11
  # geopandas will also install numpy, pandas, shapely, pyogrio, and pyproj
  - geopandas>=1.0.1
  # rasterio will also install affine
  - rasterio>=1.3.10
  # pyvista also install pooch and matplotlib
  - pyvista>=0.44.1
  - gemgis>=1.1
